/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"
#include "stdlib.h"

int *
printmessage_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code below
	 */

	printf("Received String: %s\n",*argp);
	
	result = rand();

	return &result;
}
