/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"


void
messageprog_1(char *host, char* msg)
{
	CLIENT *clnt;
	int  *result_1;
	char * printmessage_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGEPROG, MESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
		
	printmessage_1_arg = msg;
		
	result_1 = printmessage_1(&printmessage_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Message Sent. Got random number %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s <server_host> <msg>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	messageprog_1 (host, argv[2]);
exit (0);
}
